// Homework: four vertices generated by SV_VertexID, no vertex/index buffer.
struct FullscreenOut
{
    float4 Position : SV_POSITION;
    float2 Uv : TEXCOORD;
};

FullscreenOut FullscreenVS(uint vertexId : SV_VertexID)
{
    FullscreenOut output;
    output.Uv = float2(vertexId & 1u, vertexId >> 1u);
    output.Position = float4(output.Uv.x * 2.0f - 1.0f, 1.0f - output.Uv.y * 2.0f, 0.0f, 1.0f);
    return output;
}

Texture2D<float4> gSource : register(t0);
Texture2D<float4> gAlbedo : register(t1);
Texture2D<float2> gNormal : register(t2);
Texture2D<float> gDepth : register(t3);
Texture2D<float4> gBloom : register(t4);
SamplerState gLinearClamp : register(s0);

cbuffer PostProcessConstants : register(b0)
{
    float2 gInvSourceSize;
    float2 gBlurDirection;
    float gExposure;
    float gBloomThreshold;
    float gBloomStrength;
    float gVignetteStrength;
    uint gBloomEnabled;
    uint gVignetteEnabled;
    uint gDebugView;
    float gAspect;
};

// Reusable input for effects that need the G-buffer (e.g. DoF or SSAO).
struct GBufferSample
{
    float3 Albedo;
    float3 NormalW;
    float Depth;
};

GBufferSample ReadGBuffer(uint2 pixel)
{
    GBufferSample result;
    result.Albedo = gAlbedo.Load(int3(pixel, 0)).rgb;
    float2 encoded = gNormal.Load(int3(pixel, 0)) * 2.0f - 1.0f;
    float3 normal = float3(encoded, 1.0f - abs(encoded.x) - abs(encoded.y));
    float fold = saturate(-normal.z);
    normal.xy += float2(normal.x >= 0.0f ? -fold : fold, normal.y >= 0.0f ? -fold : fold);
    result.NormalW = normalize(normal);
    result.Depth = gDepth.Load(int3(pixel, 0));
    return result;
}

float3 SrgbToLinear(float3 color)
{
    return float3(color.x <= 0.04045f ? color.x / 12.92f : pow((color.x + 0.055f) / 1.055f, 2.4f),
                  color.y <= 0.04045f ? color.y / 12.92f : pow((color.y + 0.055f) / 1.055f, 2.4f),
                  color.z <= 0.04045f ? color.z / 12.92f : pow((color.z + 0.055f) / 1.055f, 2.4f));
}

float3 BrightColor(float2 uv)
{
    float3 hdr = max(gSource.SampleLevel(gLinearClamp, uv, 0).rgb, 0.0f);
    float luminance = dot(hdr, float3(0.2126f, 0.7152f, 0.0722f));
    // A soft knee avoids a sudden change when a highlight crosses the threshold.
    float knee = max(0.5f * gBloomThreshold, 0.0001f);
    float soft = clamp(luminance - gBloomThreshold + knee, 0.0f, 2.0f * knee);
    soft = soft * soft / (4.0f * knee);
    float contribution = max(luminance - gBloomThreshold, soft) / max(luminance, 0.0001f);
    return hdr * contribution;
}

float4 BloomExtractPS(FullscreenOut input) : SV_Target
{
    // Four taps downsample the HDR scene to half resolution.
    float2 offset = 0.5f * gInvSourceSize;
    float3 bright = BrightColor(input.Uv + float2(-offset.x, -offset.y));
    bright += BrightColor(input.Uv + float2(offset.x, -offset.y));
    bright += BrightColor(input.Uv + float2(-offset.x, offset.y));
    bright += BrightColor(input.Uv + float2(offset.x, offset.y));
    return float4(bright * 0.25f, 1.0f);
}

float4 GaussianBlurPS(FullscreenOut input) : SV_Target
{
    const float weights[5] = { 0.227027f, 0.1945946f, 0.1216216f, 0.054054f, 0.016216f };
    float2 step = gBlurDirection * gInvSourceSize;
    float3 color = gSource.SampleLevel(gLinearClamp, input.Uv, 0).rgb * weights[0];
    [unroll]
    for (int i = 1; i < 5; ++i)
    {
        color += gSource.SampleLevel(gLinearClamp, input.Uv + step * i, 0).rgb * weights[i];
        color += gSource.SampleLevel(gLinearClamp, input.Uv - step * i, 0).rgb * weights[i];
    }
    return float4(color, 1.0f);
}

float4 PostProcessPS(FullscreenOut input) : SV_Target
{
    // This pixel shader accepts all G-buffer textures; debug modes exercise each input.
    if (gDebugView >= 1 && gDebugView <= 3)
    {
        GBufferSample surface = ReadGBuffer(uint2(input.Position.xy));
        if (gDebugView == 1) return float4(surface.Albedo, 1.0f);
        float3 data = gDebugView == 2 ? surface.NormalW * 0.5f + 0.5f : surface.Depth.xxx;
        // Numerical debug data should retain its displayed values through the sRGB RTV.
        return float4(SrgbToLinear(saturate(data)), 1.0f);
    }

    float3 hdr = max(gSource.SampleLevel(gLinearClamp, input.Uv, 0).rgb, 0.0f);
    if (gBloomEnabled != 0)
        hdr += gBloom.SampleLevel(gLinearClamp, input.Uv, 0).rgb * gBloomStrength;
    hdr *= gExposure;
    float3 color = hdr / (1.0f + hdr); // Reinhard tone mapping, lecture slide 6.

    if (gVignetteEnabled != 0)
    {
        float2 fromCenter = (input.Uv - 0.5f) * float2(gAspect, 1.0f);
        float radius = length(fromCenter) / length(0.5f * float2(gAspect, 1.0f));
        color *= 1.0f - gVignetteStrength * smoothstep(0.25f, 1.0f, radius);
    }
    // Output stays linear. The final _SRGB RTV performs the only output encoding.
    return float4(color, 1.0f);
}
